# Generated by Django 3.2.9 on 2021-12-12 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='0102', max_length=20)),
                ('first_name', models.CharField(default='First Name', max_length=200)),
                ('last_name', models.CharField(default='Last Name', max_length=200)),
                ('phone', models.CharField(default='Phone', max_length=200)),
                ('email', models.CharField(default='email', max_length=250)),
                ('acc_status', models.CharField(default='Account Status', max_length=100)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
