# Generated by Django 3.2.9 on 2021-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_title',
            field=models.CharField(max_length=500),
        ),
    ]
