# Generated by Django 3.2.9 on 2021-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_order_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prod_id',
            field=models.CharField(default='58509', max_length=10),
        ),
    ]
