# Generated by Django 3.2.9 on 2021-12-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_order_prod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='product_price',
        ),
    ]
