# Generated by Django 3.2.9 on 2021-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='585GH938', max_length=15),
        ),
    ]
