# Generated by Django 3.2.9 on 2021-12-10 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='very fast', max_length=100)),
                ('details', models.CharField(default='something cool', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default='0102', max_length=20)),
                ('title', models.CharField(default='Post title', max_length=200)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('category', models.CharField(default='category', max_length=100)),
                ('body', models.CharField(default='Post Body', max_length=500)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
