# Generated by Django 3.2.9 on 2021-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='product_picture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='product_title',
        ),
        migrations.AddField(
            model_name='post',
            name='product_price',
            field=models.CharField(default='Product Price', max_length=200),
        ),
    ]
