# Generated by Django 3.2.9 on 2021-12-11 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0002_auto_20211210_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(default='0102', max_length=20)),
                ('product_title', models.CharField(default='Post title', max_length=200)),
                ('product_price', models.CharField(default='Product Price', max_length=200)),
                ('product_picture', models.ImageField(null=True, upload_to='products/')),
                ('product_category', models.CharField(default='category', max_length=100)),
                ('product_description', models.CharField(default='Post Body', max_length=500)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbackend.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
