# Generated by Django 3.2.9 on 2021-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0003_auto_20211211_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='prod_id',
            field=models.CharField(default='0102', max_length=20),
        ),
    ]
