# Generated by Django 3.2.9 on 2021-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0004_auto_20211211_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='Post Body'),
        ),
    ]
